import type { Metadata } from 'next';
import { Anton, Inter } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const anton = Anton({ subsets: ['latin'], weight: ['400'] });
export const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Pokedex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          anton.className,
          'text-white bg-gradient-to-tr from-orange-400 to-orange-600 flex flex-col items-center justify-between min-h-screen p-24'
        )}
      >
        {children}
      </body>
    </html>
  );
}
